theme: jekyll-theme-cayman
title: "LameJam 2020"
description: "Learn, Game, Jam: Game jam and game design talks.\nWhen? Friday May 8th - Sunday May 10th\nWhere? Herzberg Laboratories, Carleton University"
show_downloads: "false"